export const lightningControls = {
  boltAmount: {
    value: 7,
    min: 1,
    max: 20,
    step: 1,
    label: "Bolt Amount",
  },
  displacement: {
    value: 150,
    min: 50,
    max: 300,
    step: 1,
    label: "Displacement",
  },
  jaggedness: {
    value: 0.5,
    min: 0,
    max: 0.6,
    step: 0.01,
    label: "Jaggedness",
  },
  segmentPoints: {
    value: 5,
    min: 1,
    max: 10,
    step: 1,
    label: "Segment Points",
  },
  segmentDensity: {
    value: 12,
    min: 4,
    max: 30,
    step: 1,
    label: "Segment Density",
  },
  envelopeShape: {
    value: 1,
    min: 0.5,
    max: 3,
    step: 0.1,
    label: "Envelope Shape",
  },
  smoothingIterations: {
    value: 3,
    min: 0,
    max: 10,
    step: 1,
    label: "Smoothing Iterations",
  },
  lineWidth: {
    value: 1,
    min: 0.1,
    max: 10,
    step: 0.1,
    label: "Line Width",
  },
  lineWidthVariation: {
    value: 3,
    min: 0,
    max: 10,
    step: 0.5,
    label: "Line Width Variation",
  },
  opacityVariation: {
    value: 1,
    min: 0,
    max: 1,
    step: 0.1,
    label: "Opacity Variation",
  },
  boltColor1: {
    value: "#f2fec8",
    label: "Bolt Color 1",
  },
  boltColor2: {
    value: "#8f9058",
    label: "Bolt Color 2",
  },
  boltColor3: {
    value: "#d9fdff",
    label: "Bolt Color 3",
  },
  glowDistance: {
    value: 10,
    min: 1,
    max: 50,
    step: 1,
    label: "Glow Distance",
  },
  oscillationCycle: {
    value: 1,
    min: 0.1,
    max: 5,
    step: 0.5,
    label: "Oscillation Cycle (s)",
  },
};

export const borderBoltControls = {
  jaggedAmplitude: {
    value: 10,
    min: 0,
    max: 50,
    step: 0.5,
    label: "Jagged Amplitude",
  },
  jaggedFrequency1: {
    value: 0.3,
    min: 0.1,
    max: 2,
    step: 0.1,
    label: "Frequency 1",
  },
  jaggedFrequency2: {
    value: 0.7,
    min: 0.1,
    max: 2,
    step: 0.1,
    label: "Frequency 2",
  },
  jaggedFrequency3: {
    value: 1.2,
    min: 0.1,
    max: 3,
    step: 0.1,
    label: "Frequency 3",
  },
  timeScale: {
    value: 10,
    min: 1,
    max: 30,
    step: 1,
    label: "Time Scale",
  },
  randomness: {
    value: 1,
    min: 0,
    max: 5,
    step: 0.1,
    label: "Randomness",
  },
  inset: {
    value: 2,
    min: 0,
    max: 20,
    step: 1,
    label: "Inset",
  },
  borderRadius: {
    value: 8,
    min: 0,
    max: 30,
    step: 1,
    label: "Border Radius",
  },
};
