export const lightningControls = {
  boltAmount: {
    value: 7,
    min: 1,
    max: 20,
    step: 1,
    label: "Bolt Amount",
  },
  displacement: {
    value: 150,
    min: 50,
    max: 300,
    step: 1,
    label: "Displacement",
  },
  jaggedness: {
    value: 0.5,
    min: 0,
    max: 0.6,
    step: 0.01,
    label: "Jaggedness",
  },
  segmentPoints: {
    value: 5,
    min: 1,
    max: 10,
    step: 1,
    label: "Segment Points",
  },
  segmentDensity: {
    value: 12,
    min: 4,
    max: 30,
    step: 1,
    label: "Segment Density",
  },
  envelopeShape: {
    value: 1,
    min: 0.5,
    max: 3,
    step: 0.1,
    label: "Envelope Shape",
  },
  smoothingIterations: {
    value: 3,
    min: 0,
    max: 10,
    step: 1,
    label: "Smoothing Iterations",
  },
  lineWidth: {
    value: 1,
    min: 1,
    max: 10,
    step: 1,
    label: "Line Width",
  },
  lineWidthVariation: {
    value: 3,
    min: 0,
    max: 10,
    step: 0.5,
    label: "Line Width Variation",
  },
  opacityVariation: {
    value: 1,
    min: 0,
    max: 1,
    step: 0.1,
    label: "Opacity Variation",
  },
  boltColor1: {
    value: "#f2fec8",
    label: "Bolt Color 1",
  },
  boltColor2: {
    value: "#8f9058",
    label: "Bolt Color 2",
  },
  boltColor3: {
    value: "#d9fdff",
    label: "Bolt Color 3",
  },
  glowDistance: {
    value: 10,
    min: 1,
    max: 50,
    step: 1,
    label: "Glow Distance",
  },
  oscillationCycle: {
    value: 1,
    min: 0.1,
    max: 5,
    step: 0.5,
    label: "Oscillation Cycle (s)",
  },
};
